[[classOrder]]
classes = ["Pack", "Schema"]

[[classOrder]]
section = "Internal"
classes = ["Datatype", "BitReader", "BitWriter", "Reader", "Writer", "Evaluator", "Logger"]

gitSourceBranch = "main"

[home]
enabled = true