[package]
name = "isoopod/pack"
description = "Schematized Luau buffer serialization library."
version = "0.5.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/isoopod/Pack"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]

[dev-dependencies]
testez = "roblox/testez@0.4.1"
