[package]
name = "isoopod/pack"
description = "Schematized Luau buffer serialization library."
version = "0.7.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/isoopod/Pack"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
